"""Added smart_off_active

Revision ID: 455de5a3503e
Revises: eaa82f9ded8a
Create Date: 2020-11-07 16:43:36.205427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '455de5a3503e'
down_revision = 'eaa82f9ded8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('light') as batch_op:
        batch_op.add_column(
            sa.Column('smart_off_active', sa.Boolean(), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('light') as batch_op:
        batch_op.drop_column('smart_off_active')
    # ### end Alembic commands ###
